apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - metastore-db.yaml
  - hdfs.yaml
  - hive-metastore.yaml
  - trino.yaml
  - kafka.yaml
  - spark.yaml
  - airflow.yaml
  - observability.yaml
  - metabase.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: local-cdc-data-platform

configMapGenerator:
  - name: hadoop-config
    namespace: data-pipeline
    files:
      - core-site.xml=config/hadoop/core-site.xml
      - hdfs-site.xml=config/hadoop/hdfs-site.xml
  - name: hive-metastore-config
    namespace: data-pipeline
    files:
      - hive-site.xml=config/hive-metastore/hive-site.xml
  - name: trino-etc
    namespace: data-pipeline
    files:
      - config.properties=config/trino/etc/config.properties
      - jvm.config=config/trino/etc/jvm.config
      - node.properties=config/trino/etc/node.properties
  - name: trino-catalog
    namespace: data-pipeline
    files:
      - hive.properties=config/trino/catalog/hive.properties
      - iceberg.properties=config/trino/catalog/iceberg.properties
  - name: prometheus-config
    namespace: data-pipeline
    files:
      - prometheus.yml=config/prometheus/prometheus.yml
  - name: statsd-config
    namespace: data-pipeline
    files:
      - mapping.yml=config/statsd/mapping.yml
  - name: postgres-init
    namespace: data-pipeline
    files:
      - 001_create_tables.sql=config/postgres/init/001_create_tables.sql
      - 002_seed_data.sql=config/postgres/init/002_seed_data.sql
  - name: kafka-connect-config
    namespace: data-pipeline
    files:
      - postgres-cdc.json=config/connect/postgres-cdc.json
  - name: spark-jobs
    namespace: data-pipeline
    files:
      - bronze_from_kafka.py=config/spark/jobs/bronze_from_kafka.py
      - silver_payments.py=config/spark/jobs/silver_payments.py
      - gold_metrics.py=config/spark/jobs/gold_metrics.py
      - common.py=config/spark/jobs/common.py
  - name: airflow-dags
    namespace: data-pipeline
    files:
      - payments_pipeline.py=config/airflow/dags/payments_pipeline.py
  - name: pipeline-scripts
    namespace: data-pipeline
    files:
      - init_hdfs.py=config/scripts/init_hdfs.py
      - publish_trino_tables.py=config/scripts/publish_trino_tables.py
      - run_local_job.py=config/scripts/run_local_job.py
      - validate_connector.py=config/scripts/validate_connector.py
      - validate_schema.py=config/scripts/validate_schema.py
      - validate_trino.py=config/scripts/validate_trino.py
  - name: trino-validation-sql
    namespace: data-pipeline
    files:
      - validation_queries.sql=config/sql/trino/validation_queries.sql
